[package]
name = "phased_in_codes"
version = "0.1.0"
authors = ["George Liontos <sdi1600094@di.uoa.gr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base2 = "0.3.1"
bitvec = "0.19.3"
clap = "2.33.3"